apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: caimagereports.security.andreybondarenko.com
spec:
  group: security.andreybondarenko.com
  names:
    kind: CaImageReport
    plural: caimagereports
    singular: caimagereport
    shortNames:
      - cair
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                scanRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                summary:
                  type: object
                  properties:
                    totalImages:
                      type: integer
                    green:
                      type: integer
                    yellow:
                      type: integer
                    red:
                      type: integer
                report:
                  type: array
                  items:
                    type: object
                    properties:
                      image:
                        type: string
                      namespaces:
                        type: array
                        items:
                          type: string
                      certs:
                        type: array
                        items:
                          type: object
                          properties:
                            path:
                              type: string
                            subject:
                              type: string
                      status:
                        type: string
              # allow extra fields under spec if you add more later
              x-kubernetes-preserve-unknown-fields: true
