apiVersion: batch/v1
kind: Job
metadata:
  name: ca-scan-mail-20251126
  namespace: ca-scanner
  labels:
    ca-scan: ca-scan-mail
spec:
  template:
    spec:
      serviceAccountName: ca-scanner
      restartPolicy: Never
      containers:
        - name: scanner
          image: harbor.andreybondarenko.com/library/ca-scanner:latest
          args:
            - /bin/sh
            - -c
            - |
              # 1. run extractor
              python /app/ca-nitiser.py --kubectl kubectl --runtime docker > /work/images.json
              # 2. run analyser with policy from mounted ConfigMap
              python /app/ca-analyse.py --images /work/images.json --policy /policy/policy.json > /work/report.json
              # 3. apply CaImageReport from inside cluster (or post via API)
              python /app/push-report.py \
                --scan-name=ca-scan-mail \
                --scan-namespace=mail \
                --report-json=/work/report.json
          volumeMounts:
            - name: policy
              mountPath: /policy
      volumes:
        - name: policy
          configMap:
            name: ca-scan-policy
            # chosen per-namespace or global by the controller
