apiVersion: batch/v1
kind: Job
metadata:
  name: ca-scan-cluster
  namespace: ca-scanner
spec:
  template:
    spec:
      serviceAccountName: ca-scanner
      restartPolicy: Never
      containers:
        - name: scanner
          image: harbor.andreybondarenko.com/library/canitiser:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              python /app/ca-nitiser-k8s.py \
                --scan-namespace ca-scanner \
                --namespace mail \
                > /work/images.json

              python /app/ca-analyse.py \
                --images /work/images.json \
                --policy /policy/policy.json \
                > /work/report.json

              python /app/push-report.py \
                --report-json /work/report.json \
                --report-name ca-scan-cluster-report \
                --report-namespace ca-scanner \
                --scan-name ca-scan-cluster \
                --scan-namespace ca-scanner

          volumeMounts:
            - name: policy
              mountPath: /policy
            - name: work
              mountPath: /work
      volumes:
        - name: policy
          configMap:
            name: ca-scan-policy
        - name: work
          emptyDir: {}
