apiVersion: batch/v1
kind: Job
metadata:
  name: ca-scan-cluster
  namespace: ca-scanner
spec:
  template:
    spec:
      serviceAccountName: ca-scanner
      restartPolicy: Never
      containers:
        - name: scanner
          image: harbor.andreybondarenko.com/library/canitiser:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              echo "[controller] running ca-nitiser-k8s" >&2
              python /app/ca-nitiser-k8s.py \
                --scan-namespace ca-scanner \
                --namespace mail \
                --scanner-image harbor.andreybondarenko.com/library/ca-scanner-base:latest \
                > /work/images.json

              echo "[controller] images.json:" >&2
              cat /work/images.json >&2

              echo "[controller] running ca-analyse" >&2
              python /app/ca-analyse.py \
                --images /work/images.json \
                --policy /policy/policy.json \
                > /work/report.json

              echo "[controller] running push-report" >&2
              python /app/push-report.py \
                --report-json /work/report.json \
                --report-name ca-scan-mail-report \
                --report-namespace ca-scanner \
                --scan-name ca-scan-mail \
                --scan-namespace ca-scanner

          volumeMounts:
            - name: policy
              mountPath: /policy
            - name: work
              mountPath: /work
      volumes:
        - name: policy
          configMap:
            name: ca-scan-policy
        - name: work
          emptyDir: {}
